## **EV Charging Infrastructure Analysis**

*Notebook 02 — Data Audit*

This notebook performs a detailed audit of the dataset to identify potential data quality issues before the cleaning stage.

## Objectives

- Inspect the dataset structure.
- Identify missing values.
- Identify duplicated records.
- Analyze data types.
- Check unique values in categorical variables.
- Identify potential inconsistencies.
- Analyze numerical variables and their distributions.
- Identify potential outliers.

## 1. Libraries and Dataset

In [10]:
# Import libraries
import pandas as pd
import numpy as np

## 2. Load Dataset

The dataset will be loaded using Pandas' `read_csv()` function.

In [11]:
# Define dataset path
DATA_PATH = "../data/raw/global_ev_market_charging_infrastructure_2026.csv"

In [12]:
# Load dataset
df = pd.read_csv(DATA_PATH)

## 3. Missing Values

Missing values can affect data analysis and Machine Learning models. Therefore, they must be identified before the cleaning stage.

In [13]:
# Missing Values

missing_values = df.isnull().sum()
display(missing_values)

# Missing value percentage
missing_percentage = (missing_values/len(df)) * 100
display(missing_percentage)

# Missing values summary
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
    }).sort_values(by="Missing Percentage", ascending=False)

display(missing_summary)

record_id                 0
country                   0
region                    0
ev_brand                  0
vehicle_type              0
ev_sales_units            0
battery_capacity_kwh      0
vehicle_range_km          0
charging_time_hours       0
charging_stations         0
avg_ev_price_usd          0
energy_consumption_kwh    0
govt_incentives           0
market_adoption_rate      0
co2_reduction_mt          0
year                      0
dtype: int64

record_id                 0.0
country                   0.0
region                    0.0
ev_brand                  0.0
vehicle_type              0.0
ev_sales_units            0.0
battery_capacity_kwh      0.0
vehicle_range_km          0.0
charging_time_hours       0.0
charging_stations         0.0
avg_ev_price_usd          0.0
energy_consumption_kwh    0.0
govt_incentives           0.0
market_adoption_rate      0.0
co2_reduction_mt          0.0
year                      0.0
dtype: float64

                        Missing Values  Missing Percentage
record_id                            0                 0.0
country                              0                 0.0
region                               0                 0.0
ev_brand                             0                 0.0
vehicle_type                         0                 0.0
ev_sales_units                       0                 0.0
battery_capacity_kwh                 0                 0.0
vehicle_range_km                     0                 0.0
charging_time_hours                  0                 0.0
charging_stations                    0                 0.0
avg_ev_price_usd                     0                 0.0
energy_consumption_kwh               0                 0.0
govt_incentives                      0                 0.0
market_adoption_rate                 0                 0.0
co2_reduction_mt                     0                 0.0
year                                 0                 0.0

## 4. Duplicate Records

Duplicate records can lead to biased analysis and may affect Machine Learning models. We will check whether the dataset contains completely duplicated rows.

In [14]:
# Duplicated rows
duplicated_rows = df.duplicated().sum()
print(f"Number of duplicated rows: {duplicated_rows}")

Number of duplicated rows: 0

## 5. Record IDs

The `record_id` column will be analyzed to determine whether each record has a unique identifier.

In [15]:
# Unique record IDs
unique_ids = df["record_id"].nunique()
print(f"Number of records: {len(df):,}")
print(f"Number of unique IDs: {unique_ids:,}")

Number of records: 5,000
Number of unique IDs: 5,000

In [16]:
# Duplicated record IDs
duplicated_ids = df["record_id"].duplicated().sum()
print(f"Number of duplicated IDs: {duplicated_ids}")

Number of duplicated IDs: 0

## 6. Categorical Variables

Categorical variables will be inspected to identify their unique values and detect potential inconsistencies.

In [17]:
categorical_columns = df.select_dtypes(include=object).columns
print("Categorical columns:")
print(categorical_columns)

Categorical columns:
Index(['record_id', 'country', 'region', 'ev_brand', 'vehicle_type',
       'govt_incentives'],
      dtype='str')

C:\Users\PICHAU\AppData\Local\Temp\ipykernel_19644\2087588700.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=object).columns

In [18]:
# Country values
display(df["country"].value_counts())

country
Canada            541
India             512
Australia         509
Japan             503
China             500
Norway            499
United States     498
France            492
Germany           481
United Kingdom    465
Name: count, dtype: int64

In [19]:
# Region values
display(df["region"].value_counts())

region
Europe           1937
Asia             1515
North America    1039
Oceania           509
Name: count, dtype: int64

In [20]:
# Vehicle type values
display(df["vehicle_type"].value_counts())

vehicle_type
Truck    1292
Car      1276
SUV      1239
Bus      1193
Name: count, dtype: int64

In [21]:
# Government incentive categories
display(df["govt_incentives"].value_counts())

govt_incentives
No     2548
Yes    2452
Name: count, dtype: int64

## 7. Numerical Variables

Numerical variables will be analyzed using descriptive statistics to identify their ranges, central tendencies, and potential anomalies.

In [22]:
# Identify numerical columns
numerical_columns = df.select_dtypes(include=np.number).columns

print("Numerical columns:")
print(numerical_columns)

Numerical columns:
Index(['ev_sales_units', 'battery_capacity_kwh', 'vehicle_range_km',
       'charging_time_hours', 'charging_stations', 'avg_ev_price_usd',
       'energy_consumption_kwh', 'market_adoption_rate', 'co2_reduction_mt',
       'year'],
      dtype='str')

In [23]:
# Descriptive statistics
display(df[numerical_columns].describe().T)

,count,mean,std,min,25%,50%,75%,max
ev_sales_units,5000.0,450391.774000,258494.794603,5142.0,224814.00,455096.50,673542.000,899978.0
battery_capacity_kwh,5000.0,79.753800,23.474791,40.0,59.00,79.00,100.000,120.0
vehicle_range_km,5000.0,450.278000,116.325407,250.0,349.00,451.00,550.000,650.0
charging_time_hours,5000.0,1.742614,0.719029,0.5,1.12,1.73,2.360,3.0
charging_stations,5000.0,100851.553400,56905.671677,574.0,52215.50,100946.00,149655.250,199969.0
avg_ev_price_usd,5000.0,55633.191800,17289.560508,25000.0,40567.75,56057.00,70821.500,84999.0
energy_consumption_kwh,5000.0,18.527740,3.749015,12.0,15.30,18.45,21.800,25.0
market_adoption_rate,5000.0,34.848660,17.276752,5.0,19.80,34.80,49.600,65.0
co2_reduction_mt,5000.0,153.196280,84.829245,5.1,80.00,152.85,228.425,300.0
year,5000.0,2026.000000,0.000000,2026.0,2026.00,2026.00,2026.000,2026.0

## 8. Unique Values

The number of unique values in each numerical variable will be inspected to identify potential inconsistencies or unexpected values.

In [24]:
# Number of unique values
unique_values = df[numerical_columns].nunique()

display(unique_values)

ev_sales_units            4987
battery_capacity_kwh        81
vehicle_range_km           401
charging_time_hours        251
charging_stations         4941
avg_ev_price_usd          4792
energy_consumption_kwh     131
market_adoption_rate       601
co2_reduction_mt          2413
year                         1
dtype: int64

## 9. Numerical Ranges

Minimum and maximum values will be inspected to identify potentially invalid or unrealistic values.

In [25]:
# Minimum values
display(df[numerical_columns].min())

ev_sales_units             5142.0
battery_capacity_kwh         40.0
vehicle_range_km            250.0
charging_time_hours           0.5
charging_stations           574.0
avg_ev_price_usd          25000.0
energy_consumption_kwh       12.0
market_adoption_rate          5.0
co2_reduction_mt              5.1
year                       2026.0
dtype: float64

In [26]:
# Minimum values
display(df[numerical_columns].min())

ev_sales_units             5142.0
battery_capacity_kwh         40.0
vehicle_range_km            250.0
charging_time_hours           0.5
charging_stations           574.0
avg_ev_price_usd          25000.0
energy_consumption_kwh       12.0
market_adoption_rate          5.0
co2_reduction_mt              5.1
year                       2026.0
dtype: float64

## 10. Market Adoption Rate

The market adoption rate will be inspected separately because it represents a rate and should follow a specific range.

In [27]:
# Market adoption rate range
print(f"Minimum: {df['market_adoption_rate'].min()}")
print(f"Maximum: {df['market_adoption_rate'].max()}")

Minimum: 5.0
Maximum: 65.0

## 11. Year Distribution

The distribution of records across years will be inspected to identify the temporal range and potential inconsistencies.

In [28]:
# Year range
print(f"Minimum year: {df['year'].min()}")
print(f"Maximum year: {df['year'].max()}")

Minimum year: 2026
Maximum year: 2026

## 14. Audit Summary

The data audit was performed to identify potential quality issues before applying any cleaning or transformation.

The following aspects were evaluated:

- Dataset dimensions
- Data types
- Missing values
- Duplicate records
- Unique record identifiers
- Categorical variables
- Numerical variables
- Numerical ranges
- Market adoption rate
- Year distribution

No data transformations were performed during this stage. The identified issues will be evaluated and addressed in the Data Cleaning stage.